### ISSUE TITLE
该项目是想已 jcenter库的形式提供？还是直接做成一个工具类的App？

### ISSUE THREAD

**Issue by AllenCoder** [android-notes/SwissArmyKnife#1]
看完使用说明，拉了一下最新代码，运行生成了一个APP，但是无启动图标，无法运行。
但是如果作为aar方式提供的话，目前文档和接入步骤都不够完善

**Comment by android-notes** [comment]
今天刚上传到jcenter，还在审核，最近几天应该就可以用了

**Comment by xhAndroid** [comment]
同问：目前文档和接入步骤都不够完善
