### ISSUE TITLE
程序运行后，点击悬浮窗一会就会堆栈溢出

### ISSUE THREAD

**Issue by spiritedRunning** [android-notes/SwissArmyKnife#15]
java.lang.StackOverflowError
stack size 8MB

1 com.wanjian.sak.view.DrawingBoardView.dispatchTouchEvent(DrawingBoardView.java:49)
2 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2602)
3 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
4 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2602)
5 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
6 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
7 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
8 android.app.Activity.dispatchTouchEvent(Activity.java:3061)
9 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
10 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2602)
11 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)

然后app马上卡死，只能重启。 Nexus 5x 7.0

**Comment by android-notes** [comment]
你用的是哪个版本的sak，最新版的是 compile 'com.wanjian:sak:0.1.2.8，这个版本中DrawingBoardView里已经没有dispatchTouchEvent这个方法了  @spiritedRunning

**Comment by spiritedRunning** [comment]
@android-notes 用的是1.2.4，更新之后已经好了，只是感觉还是比较卡的

**Comment by android-notes** [comment]
不要所有选项都打开，尤其是强制图片宽高选项，在mx5上流畅度还是可以接受的
