### ISSUE TITLE
Attribute **  has already been defined如何解决？

### ISSUE THREAD

**Issue by guangdeshishe** [android-notes/SwissArmyKnife#3]
Error:(1065) Attribute "windowActionBar" has already been defined
Error:(1065) Attribute "windowNoTitle" has already been defined
Error:(1065) Attribute "windowActionBarOverlay" has already been defined
Error:(1065) Attribute "windowActionModeOverlay" has already been defined
Error:(1065) Attribute "windowFixedWidthMajor" has already been defined
Error:(1065) Attribute "windowFixedHeightMinor" has already been defined
Error:(1065) Attribute "windowFixedWidthMinor" has already been defined
Error:(1065) Attribute "windowFixedHeightMajor" has already been defined
Error:(1065) Attribute "windowMinWidthMajor" has already been defined
Error:(1065) Attribute "windowMinWidthMinor" has already been defined
Error:(1065) Attribute "actionBarTabStyle" has already been defined
Error:(1065) Attribute "actionBarTabBarStyle" has already been defined
Error:(1065) Attribute "actionBarTabTextStyle" has already been defined
Error:(1065) Attribute "actionOverflowButtonStyle" has already been defined
Error:(1065) Attribute "actionOverflowMenuStyle" has already been defined
Error:(1065) Attribute "actionBarPopupTheme" has already been defined
Error:(1065) Attribute "actionBarStyle" has already been defined
Error:(1065) Attribute "actionBarSplitStyle" has already been defined
Error:(1065) Attribute "actionBarTheme" has already been defined
Error:(1065) Attribute "actionBarWidgetTheme" has already been defined

**Comment by android-notes** [comment]
这个看样不是sak引起的，去掉 compile 'com.wanjian:sak:0.0.2' 还报错吗
