### ISSUE TITLE
这个直尺怎么关闭 是不是有bug啊

### ISSUE THREAD

**Issue by liudao01** [android-notes/SwissArmyKnife#4]
这个直尺怎么关闭 是不是有bug啊

**Comment by liudao01** [comment]
下面这几个貌似关闭不了啊

**Comment by android-notes** [comment]
后续会提供关闭功能，谢谢支持

**Comment by liudao01** [comment]
可以的兄弟  我也最近在写类似的工具 包括检测网络请求链接 以及崩溃信息 的工具库  抽空 我们看看能不能合并下哈  尽一份力

**Comment by liudao01** [comment]
顺便问下 你上传代码中心是哪里的?使用方式

compile 'com.wanjian:sak:0.0.2'  我也想搞个

**Comment by hike2008** [comment]
赞

**Comment by android-notes** [comment]
ok

**Comment by nantofu** [comment]
同样发现支持无法关闭，作者最近有更新计划么？

**Comment by android-notes** [comment]
第一个版本急于实现功能，现在已经开始准备第二个版本，预计一个月内发布第二个版本，原有功能不变，修复已知的bug，新增用户自定义功能

**Comment by nantofu** [comment]
@android-notes 好的多谢

**Comment by android-notes** [comment]
第二个版本测试版 已提交到master 和 ver2分支,修复了直尺无法关闭等bug，具体更新详见 README.md  @liudao01   @nantofu
