### ISSUE TITLE
app 多进程情况下可能产生多个入口图标

### ISSUE THREAD

**Issue by spiritedRunning** [android-notes/SwissArmyKnife#5]
没有验证，从现象看是这样，而且两个的显示结果会重叠，基本看不清东西。

**Comment by spiritedRunning** [comment]
提供一张图
https://drive.google.com/open?id=0B9hkUn7mRJB0VVB2M0p0UWlEZW8

**Comment by android-notes** [comment]
最新版的还有这种情况吗

**Comment by chordw** [comment]
悬浮的机器人按钮实现原理是什么？

**Comment by android-notes** [comment]
((FrameLayout)activity.getWindow().getDecorView()).addView(机器人imageview)

**Comment by spiritedRunning** [comment]
用了最新版本，看起来已经好了，但是每次都会堆栈溢出。

**Comment by android-notes** [comment]
可以贴一下日志吗，用的什么手机，系统版本是多少 @spiritedRunning
